#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

#include <Arduino.h>

// This file will be auto-generated by the build script
// It contains the embedded HTML for the web interface

extern const char WEB_HTML[] PROGMEM;

#endif // WEB_ASSETS_H
