# Pre-build script for PlatformIO
# This script runs before the build process and embeds config.json and web HTML

Import("env")
import json
import os

print("Pre-build script running...")
print("Building for board: " + env.BoardConfig().get("name"))

# Paths
project_dir = env.get("PROJECT_DIR")
config_json_path = os.path.join(project_dir, "data", "config.json")
config_manager_path = os.path.join(project_dir, "src", "Core", "ConfigManager.cpp")
web_html_path = os.path.join(project_dir, "data", "web", "index.html")
web_assets_cpp_path = os.path.join(project_dir, "src", "Network", "WebAssets.cpp")

# 1. Embed config.json
print(f"Embedding config.json into ConfigManager.cpp...")

try:
    # Read and minify config.json
    with open(config_json_path, 'r') as f:
        config_data = json.load(f)

    # Convert to minified JSON string (no extra whitespace)
    minified_json = json.dumps(config_data, separators=(',', ':'))

    # Escape quotes for C++ string
    escaped_json = minified_json.replace('"', '\\"')

    # Read the current ConfigManager.cpp
    with open(config_manager_path, 'r') as f:
        config_manager_content = f.read()

    # Find and replace the DEFAULT_CONFIG line
    lines = config_manager_content.split('\n')
    modified = False

    for i, line in enumerate(lines):
        if line.strip().startswith('const char PROGMEM DEFAULT_CONFIG[]'):
            lines[i] = f'const char PROGMEM DEFAULT_CONFIG[] = "{escaped_json}";'
            modified = True
            break

    if modified:
        with open(config_manager_path, 'w') as f:
            f.write('\n'.join(lines))
        print(f"[OK] Config embedded successfully ({len(minified_json)} bytes)")
    else:
        print("[WARNING] Could not find DEFAULT_CONFIG line in ConfigManager.cpp")

except FileNotFoundError as e:
    print(f"[WARNING] Could not find file: {e.filename}")
except Exception as e:
    print(f"[WARNING] Error embedding config: {str(e)}")

# 2. Embed web HTML
print(f"Embedding index.html into WebAssets.cpp...")

try:
    # Read HTML file
    with open(web_html_path, 'r', encoding='utf-8') as f:
        html_content = f.read()

    # Escape special characters for C++ string
    html_content = html_content.replace('\\', '\\\\')
    html_content = html_content.replace('"', '\\"')
    html_content = html_content.replace('\n', '\\n')
    html_content = html_content.replace('\r', '')

    # Generate C++ source file
    cpp_content = f'''#include "Network/WebAssets.h"

// Auto-generated file - do not edit manually
// This file is generated by scripts/pre_build.py

const char WEB_HTML[] PROGMEM = "{html_content}";
'''

    # Write to source file
    with open(web_assets_cpp_path, 'w', encoding='utf-8') as f:
        f.write(cpp_content)

    print(f"[OK] HTML embedded successfully ({len(html_content)} bytes)")

except FileNotFoundError as e:
    print(f"[WARNING] Could not find file: {e.filename}")
except Exception as e:
    print(f"[WARNING] Error embedding HTML: {str(e)}")

print("Pre-build script completed")